name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    ############################################
    # 1. Analyse SAST avec CodeQL
    ############################################
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: Run CodeQL analysis
      uses: github/codeql-action/analyze@v3

    ############################################
    # 2. Analyse sécurité Python avec Bandit
    ############################################
    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r api --severity-level high -f json -o bandit-report.json

    ############################################
    # 3. Build Docker
    ############################################
    - name: Build Docker image
      run: docker build -t devsecops-api .

    ############################################
    # 4. Scan Docker avec Trivy
    ############################################
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        image-ref: devsecops-api
        severity: CRITICAL,HIGH
        exit-code: 1
        format: json
        output: trivy-report.json

    ############################################
    # 5. Upload security reports (optionnel)
    ############################################
    - name: Upload Bandit report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: bandit-report.json

    - name: Upload Trivy report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy-report.json
